# Generated by Django 2.2.12 on 2020-04-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('bionominal', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('water_freq', models.IntegerField()),
                ('fertilizer_freq', models.IntegerField()),
            ],
        ),
    ]
